# Generated by Django 3.2.8 on 2021-11-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.IntegerField(max_length=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_short_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentShiftInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=10)),
                ('batch_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentbatch')),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentbranch')),
                ('professor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherinfo')),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsectioninfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('admission_date', models.DateField()),
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('student_img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('batch_year', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='students.studentbatch')),
                ('section_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsectioninfo')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentshiftinfo')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsubjectinfo')),
            ],
            options={
                'unique_together': {('usn', 'subject_name')},
            },
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentbatch')),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentbranch')),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsectioninfo')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentinfo')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
