# Generated by Django 3.2.8 on 2021-12-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.IntegerField(max_length=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('usn', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('student_img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('sub1_att', models.IntegerField(null=True)),
                ('sub2_att', models.IntegerField(null=True)),
                ('sub3_att', models.IntegerField(null=True)),
                ('sub4_att', models.IntegerField(null=True)),
                ('sub5_att', models.IntegerField(null=True)),
                ('sub6_att', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSem',
            fields=[
                ('sem_number', models.IntegerField(max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentShiftInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectInfo',
            fields=[
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentbranch')),
            ],
        ),
    ]
