# Generated by Django 3.2.8 on 2021-12-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectinfo',
            name='professor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherinfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='batch_year',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='students.studentbatch'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentbranch'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='lab1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab1', to='students.studentsubjectinfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='lab2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab2', to='students.studentsubjectinfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='section_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsectioninfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentshiftinfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='sub1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub1', to='students.studentsubjectinfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='sub2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub2', to='students.studentsubjectinfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='sub3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub3', to='students.studentsubjectinfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='sub4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub4', to='students.studentsubjectinfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='sub5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub5', to='students.studentsubjectinfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='sub6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub6', to='students.studentsubjectinfo'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='studentinfo',
            unique_together={('usn',)},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
