# Generated by Django 3.2.8 on 2021-11-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
                ('subject_code', models.CharField(max_length=10)),
                ('batch_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentbatch')),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentbranch')),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsectioninfo')),
            ],
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsubjectinfo'),
        ),
        migrations.DeleteModel(
            name='StudentClassInfo',
        ),
    ]
