# Generated by Django 3.2.8 on 2021-12-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSem',
            fields=[
                ('sem_number', models.IntegerField(max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentinfo',
            unique_together={('usn',)},
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='subject_name',
        ),
    ]
