# Generated by Django 3.2.8 on 2021-11-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentshiftinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentshiftinfo',
            name='shift_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
