# Generated by Django 3.2.8 on 2021-11-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='usn',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
