# Generated by Django 3.2.8 on 2021-11-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclassinfo',
            name='section_name',
        ),
    ]
