# Generated by Django 3.2.8 on 2021-12-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubjectinfo',
            name='batch_year',
        ),
        migrations.RemoveField(
            model_name='studentsubjectinfo',
            name='section_name',
        ),
    ]
