# Generated by Django 3.2.8 on 2021-11-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatch',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentbranch',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsectioninfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='batch_year',
            field=models.IntegerField(default='2019', max_length=4),
        ),
        migrations.AlterField(
            model_name='studentbranch',
            name='branch_short_name',
            field=models.CharField(default='cse', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentclassinfo',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentbranch'),
        ),
        migrations.AlterField(
            model_name='studentclassinfo',
            name='class_short_form',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentclassinfo',
            name='section_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsectioninfo'),
        ),
        migrations.AlterField(
            model_name='studentsectioninfo',
            name='section_name',
            field=models.CharField(default='A', max_length=20),
        ),
    ]
