# Generated by Django 3.2.8 on 2021-11-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211123_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubjectinfo',
            name='batch_year',
        ),
        migrations.RemoveField(
            model_name='studentsubjectinfo',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='studentsubjectinfo',
            name='section_name',
        ),
    ]
