# Generated by Django 3.2.8 on 2021-11-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentclassinfo_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclassinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='studentclassinfo',
            name='section_name',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.CASCADE, to='students.studentsectioninfo'),
        ),
        migrations.AlterField(
            model_name='studentclassinfo',
            name='class_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
