# Generated by Django 3.2.8 on 2021-11-22 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211122_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='admission_id',
            new_name='usn',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='batch_year',
            field=models.ForeignKey(default=2019, max_length=4, on_delete=django.db.models.deletion.CASCADE, to='students.studentbatch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsubjectinfo',
            name='subject_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='studentinfo',
            unique_together={('usn', 'class_type')},
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='fathers_img',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='fathers_nid',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='fathers_number',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='mothers_img',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='mothers_nid',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='mothers_number',
        ),
    ]
