# Generated by Django 3.2.8 on 2021-11-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211123_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='subject_name',
            new_name='class_type',
        ),
        migrations.AddField(
            model_name='studentbatch',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentbranch',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsectioninfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentshiftinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsubjectinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='batch_year',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='studentbranch',
            name='branch_short_name',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='usn',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='studentsectioninfo',
            name='section_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentshiftinfo',
            name='shift_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsubjectinfo',
            name='subject_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='studentinfo',
            unique_together={('usn', 'class_type')},
        ),
    ]
