# Generated by Django 3.2.8 on 2021-12-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211201_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassName',
        ),
    ]
