# Generated by Django 3.2.8 on 2021-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211203_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='usn',
            field=models.CharField(max_length=10),
        ),
    ]
