# Generated by Django 3.2.8 on 2021-12-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20211204_2215'),
        ('students', '0003_alter_studentsubjectinfo_professor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubjectinfo',
            name='professor_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherinfo'),
        ),
    ]
