# Generated by Django 3.2.8 on 2021-11-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0003_auto_20211122_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectinfo',
            name='professor_name',
            field=models.ForeignKey(default='Prashant Naik', on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherinfo'),
            preserve_default=False,
        ),
    ]
