# Generated by Django 3.2.9 on 2021-12-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentsubjectinfo_professor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='sub1_att',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sub2_att',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sub3_att',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sub4_att',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sub5_att',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sub6_att',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
