# Generated by Django 3.2.8 on 2021-12-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20211207_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsem',
            name='sem_name',
            field=models.CharField(default='Third', max_length=10),
            preserve_default=False,
        ),
    ]
