# Generated by Django 3.2.8 on 2021-11-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20211122_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsectioninfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentsectioninfo',
            name='section_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
