# Generated by Django 3.2.8 on 2021-12-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentsem_sem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='sem_name',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='students.studentsem'),
            preserve_default=False,
        ),
    ]
