# Generated by Django 3.2.8 on 2021-12-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentinfo_sem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsem',
            name='end_date',
            field=models.DateField(default='2022-01-31'),
        ),
        migrations.AddField(
            model_name='studentsem',
            name='start_date',
            field=models.DateField(default='2021-08-02'),
        ),
        migrations.AddField(
            model_name='studentsubjectinfo',
            name='sem_name',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='students.studentsem'),
        ),
    ]
