# Generated by Django 3.2.8 on 2021-12-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20211231_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsubjectinfo',
            old_name='sem_name',
            new_name='sem_number',
        ),
    ]
