# Generated by Django 3.2.8 on 2022-01-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_studentinfo_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_img',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
