# Generated by Django 3.2.8 on 2022-01-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_studentinfo_student_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='att_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
