# Generated by Django 3.2.8 on 2022-01-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20220105_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='ext_class_lab1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='ext_class_lab2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='ext_class_sub1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='ext_class_sub2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='ext_class_sub3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='ext_class_sub4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='ext_class_sub5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='ext_class_sub6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='lab1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab1', to='students.studentsubjectinfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='lab2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab2', to='students.studentsubjectinfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sub1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub1', to='students.studentsubjectinfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sub2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub2', to='students.studentsubjectinfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sub3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub3', to='students.studentsubjectinfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sub4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub4', to='students.studentsubjectinfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sub5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub5', to='students.studentsubjectinfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sub6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub6', to='students.studentsubjectinfo'),
        ),
    ]
