# Generated by Django 3.2.8 on 2022-01-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20220107_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='ext_class_lab1',
            new_name='extra_class_lab1',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='ext_class_lab2',
            new_name='extra_class_lab2',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='ext_class_sub1',
            new_name='extra_class_sub1',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='ext_class_sub2',
            new_name='extra_class_sub2',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='ext_class_sub3',
            new_name='extra_class_sub3',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='ext_class_sub4',
            new_name='extra_class_sub4',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='ext_class_sub5',
            new_name='extra_class_sub5',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='ext_class_sub6',
            new_name='extra_class_sub6',
        ),
    ]
