# Generated by Django 3.2.8 on 2021-12-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='salary',
        ),
    ]
