# Generated by Django 3.2.8 on 2021-12-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentsubjectinfo_professor_name'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='sub1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psub1', to='students.studentsubjectinfo'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='sub2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psub2', to='students.studentsubjectinfo'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='sub3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psub3', to='students.studentsubjectinfo'),
        ),
    ]
