# Generated by Django 3.2.8 on 2021-12-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
