# Generated by Django 3.2.8 on 2021-12-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20211203_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='sub_type',
        ),
        migrations.DeleteModel(
            name='TeacherSubInfo',
        ),
    ]
